base_config:
- config/train_base_config.yaml
- config/dataset/dataset_train.yaml
- config/dataset/dataset_val.yaml


pipeline:
  name: StableMTLPipeline
  kwargs:
    scale_invariant: true
    shift_invariant: true
    input_noise: deterministic

# Training settings
trainer:
  attn_mask_ratio: 0.4
  attn_mask_type: attn_prob # attn_prob, random, highest, top_random_k
  return_feature: afterSelfAttn_residual # afterSelfAttn_residual
  sep_QKV: true
  main_stream_from_scratch: false
  use_long_range_attn: false
  exclude_mainstream_output_type: true
  n_attns: 4
 
  unet_weight_path: ./checkpoints/single_stream_unet.pth
  


  prob_drop_second_frame: 0.0
  output_types:
    - normal
    - depth
    - semantic
    - optical_flow
    - scene_flow
    - albedo
    - shading

  output_losses:
    - normal
    - depth
    - semantic
    - optical_flow
    - scene_flow
    - albedo
    - shading

  apply_task_attn_to_layers: all  # all, dec


lr: 1.0e-04
max_iter: 11000

dataloader:
  num_workers: 16
  iterative_sampling: true
  effective_batch_size: 32
  max_train_batch_size: 16
  seed: 2024  # to ensure continuity when resuming from checkpoint
